### ISSUE TITLE
Error when starting GT:MP Server

### ISSUE THREAD

**Issue by thephilluk** [Samppaa/GTA-RP#43]
Hello,

Error when starting GT:MP server with the GTA-RP Ressource loaded: [Pastebin Server Log](https://pastebin.com/yaVsL8yC)

Config.ini File: [Pastebin Config ini](https://pastebin.com/EyaJdrNY)

settings.xml file: [Pastebin server XML](https://pastebin.com/hFuYGSVn)

**Comment by sjlehtonen** [comment]
Are you sure that the Config.ini is in the right location? Also can you connect to the mysql database successfully? I don't immediately see anything wrong with your files but you should remove the "admin" and "speedometer" mods from the settings.xml

**Comment by thephilluk** [comment]
Hey,

I tried different locations for the Config.ini, always inside the folder "Config": Server Root/Config, resources/Config, game-mode Root(Server-Root/resources/GTA-RP/Config).
I just tried it without the "Config" folder, with no success.

I can successfully connect to the Database using the Workbench,

other resources unloaded, still the same error.

if you need any more info, please let me know.

**Comment by sjlehtonen** [comment]
Are you using the stable version of the GTA-MP or the beta version? I haven't tested with the beta version so there might be problems with it. If it is the stable version, it should work okay.

EDIT: I think I fixed the bug now, it should work properly. Tell me if there is still problems. 

I am in china for few months so I can't test the mod easily with this mac laptop now, so tell if it's still broken.

**Comment by thephilluk** [comment]
redownloaded the stable version of the Mod, Issue persists. Just tested the MySQL account used by the Gamemode, access to every Table and able to execute Queries. Tried moving the Config.ini around again, still broken.

Maybe something wrong with the DB Model?

**Comment by sjlehtonen** [comment]
Did you update your game mode from this repo? I updated it today and it worked fine when I tested it today on my laptop.

**Comment by thephilluk** [comment]
I downloaded the Zip, deleted the GTA-RP Folder inside the ressources folder, moved the Folder out of the ZIP and renamed it.

Still no success...

**Comment by sjlehtonen** [comment]
Is it still the same error as before? Are you running on windows or linux?

It's very weird because I just tested 5 minutes ago and it works perfectly, the server starts up and loads everything.

If the error is different as before, can you post it?

**Comment by thephilluk** [comment]
Hi,

sorry for the long pause,

it is still the same error, running on Win10 x64
